### ISSUE TITLE
phpcr shell documentation link not found

### ISSUE THREAD

**Issue by dbu** [phpcr/phpcr.github.io#33]
the link to the phpcr-shell documentation in the tools section http://phpcr.github.io/tools/ goes to http://phpcr.github.io/documentation/phpcr-shell which does not exist. any idea what went wrong? we should add a little doc how to update the phpcr-docs in phpcr.github.io i think - i don't know (or don't remember) how we integrated it.

**Comment by dantleech** [comment]
its hosted on readthedocs now, I've updated the link. Not sure what happened to the original page ..

**Comment by dbu** [comment]
thanks
